language: ruby
rvm:
- 2.3.1
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
script:
  - bundle exec rspec
  - bundle exec rubocop
notifications:
  email:
    on_success: never
    on_failur: always